export { default as VideoMeetingsHeroSection } from "./VideoMeetingsHeroSection";
export { default as VideoMeetingsContinuitySection } from "./VideoMeetingsContinuitySection";
export { default as VideoMeetingsShowcaseSection } from "./VideoMeetingsShowcaseSection";
export { default as VideoMeetingsCoreCapabilitiesSection } from "./VideoMeetingsCoreCapabilitiesSection";
export { default as VideoMeetingsCollaborationSection } from "./VideoMeetingsCollaborationSection";
export { default as VideoMeetingsAIIntelligenceSection } from "./VideoMeetingsAIIntelligenceSection";
export { default as UseCasesSection } from "./UseCasesSection";
export { default as TestimonialSection} from "./TestimonialSection";
export { default as PricingSection } from "./PricingSection";
export { default as FAQSection } from "./FAQSection";
