"use client";

import { useEffect, useRef, useState } from "react";
import {
  FiVideo,
  FiStar,
  FiCheckSquare,
  FiUserCheck,
  FiCalendar,
  FiClock,
  FiAlertTriangle,
  FiLink2,
} from "react-icons/fi";
import type { IconType } from "react-icons";

// Reusable scroll-in-view hook (same pattern as the other sections)
function useInView(threshold = 0.15) {
  const ref = useRef<HTMLDivElement>(null);
  const [inView, setInView] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const obs = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setInView(true);
          obs.disconnect();
        }
      },
      { threshold }
    );
    obs.observe(el);
    return () => obs.disconnect();
  }, [threshold]);

  return { ref, inView };
}

type Signal = {
  icon: IconType;
  title: string;
  description: string;
};

const SIGNALS: Signal[] = [
  {
    icon: FiVideo,
    title: "Meeting held",
    description:
      "A scheduled or started meeting created a source event, with date and participants.",
  },
  {
    icon: FiStar,
    title: "Summary reviewed",
    description:
      "A human reviewed or edited the meeting summary before it was relied on or shared.",
  },
  {
    icon: FiCheckSquare,
    title: "Decision logged",
    description:
      "A decision was captured and linked to its source meeting, thread, or space.",
  },
  {
    icon: FiUserCheck,
    title: "Owner accepted",
    description:
      "A task or follow-up has a named, responsible owner who accepted it.",
  },
  {
    icon: FiCalendar,
    title: "Due date set",
    description:
      "A next step includes date or milestone context, with reminder state.",
  },
  {
    icon: FiClock,
    title: "Status changed",
    description:
      "Work moved from open to in progress, blocked, done, or escalated — with reason.",
  },
  {
    icon: FiAlertTriangle,
    title: "Risk escalated",
    description:
      "A blocker or unresolved question was surfaced for review with an escalation path.",
  },
  {
    icon: FiLink2,
    title: "Audit link created",
    description:
      "The work record links back to its meeting, summary, decision, task, or approval source.",
  },
];

export function ProofSignalsSection() {
  const { ref: eyebrowRef, inView: eyebrowIn } = useInView(0.4);
  const { ref: headRef, inView: headIn } = useInView(0.3);
  const { ref: subRef, inView: subIn } = useInView(0.3);
  const { ref: gridRef, inView: gridIn } = useInView(0.1);

  return (
    <>
      <style>{`
        @keyframes psFadeUp {
          from { opacity: 0; transform: translateY(28px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .ps-hidden  { opacity: 0; transform: translateY(28px); }
        .ps-visible { animation: psFadeUp .7s cubic-bezier(.22,1,.36,1) forwards; }

        .ps-card {
          transition: transform .3s cubic-bezier(.22,1,.36,1), box-shadow .3s ease, border-color .3s ease;
        }
        .ps-card:hover {
          transform: translateY(-4px);
          box-shadow: 0 18px 40px rgba(79,91,213,0.14);
          border-color: rgba(79,91,213,0.35);
        }

        @media (prefers-reduced-motion: reduce) {
          .ps-hidden, .ps-visible { opacity: 1 !important; transform: none !important; animation: none !important; }
          .ps-card:hover { transform: none !important; }
        }
      `}</style>

      <section
        aria-label="Proof signals — what verified work means"
        className="w-full bg-white py-20 dark:bg-[#0D0B24] sm:py-24"
      >
        <div className="mx-auto w-full max-w-7xl px-6 sm:px-8">
          {/* Header */}
          <div className="mx-auto max-w-2xl text-center">
            <p
              ref={eyebrowRef}
              className={`ps-hidden ${eyebrowIn ? "ps-visible" : ""} mb-4 text-[12px] font-bold uppercase tracking-[0.22em] text-[#4F5BD5] dark:text-[#7C86F0]`}
            >
              Proof signals
            </p>

            <h2
              ref={headRef}
              className={`ps-hidden ${headIn ? "ps-visible" : ""} mb-4 text-[clamp(28px,4.5vw,40px)] font-bold leading-[1.15] tracking-tight text-gray-900 dark:text-white`}
              style={{ animationDelay: "0.08s" }}
            >
              What &ldquo;verified work&rdquo; actually means
            </h2>

            <p
              ref={subRef}
              className={`ps-hidden ${subIn ? "ps-visible" : ""} mx-auto max-w-xl text-[15px] leading-[1.7] text-gray-500 dark:text-gray-400`}
              style={{ animationDelay: "0.16s" }}
            >
              Truth signals are generated by legitimate collaboration activity
              and governed by workspace permissions — never by monitoring people.
            </p>
          </div>

          {/* Cards */}
          <div
            ref={gridRef}
            className="mt-14 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4"
          >
            {SIGNALS.map((signal, i) => {
              const Icon = signal.icon;
              return (
                <div
                  key={signal.title}
                  className={`ps-card ps-hidden ${gridIn ? "ps-visible" : ""} rounded-2xl border border-gray-100 bg-white p-6 shadow-[0_1px_2px_rgba(16,24,40,0.04)] dark:border-white/10 dark:bg-[#151233] dark:shadow-none`}
                  style={{ animationDelay: `${0.1 + i * 0.06}s` }}
                >
                  <span className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEF0FB] text-[#4F5BD5] dark:bg-[#4F5BD5]/20 dark:text-[#8C95F2]">
                    <Icon className="h-5 w-5" aria-hidden="true" />
                  </span>
                  <h3 className="mb-2 text-[15px] font-semibold text-gray-900 dark:text-white">
                    {signal.title}
                  </h3>
                  <p className="text-[13px] leading-[1.6] text-gray-500 dark:text-gray-400">
                    {signal.description}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>
    </>
  );
}

export default ProofSignalsSection;